# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='favorite',
            new_name='is_favorite',
        ),
    ]
