# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
